-- DDL(Data Definition Language - CREATE, ALTER, DROP)
-- ALTER (오라클 객체)

-- ALTER를 이용한 제약조건 추가, 수정, 이름변경 해보기! (객체의 수정)
-- 칼럼 추가, 칼럼 수정, 칼럼 삭제도 가능함

CREATE TABLE USER_FOREIGNKEY_COPY AS SELECT * FROM USER_FOREIGNKEY; -- 테이블 복제해서 생성
SELECT * FROM USER_FOREIGNKEY_COPY;
DESC USER_FOREIGNKEY_COPY; -- 스키마출력

-- 테이블에 칼럼 추가
ALTER TABLE USER_FOREIGNKEY_COPY ADD USER_DATE DATE;
DESC USER_FOREIGNKEY_COPY;

-- 테이블에 칼럼 삭제
ALTER TABLE USER_FOREIGNKEY_COPY DROP COLUMN USER_DATE;
DESC USER_FOREIGNKEY_COPY;

-- 테이블에 칼럼 추가(USER_POINT VARCHAR2(10))
ALTER TABLE USER_FOREIGNKEY_COPY ADD USER_POINT VARCHAR2(10);
DESC USER_FOREIGNKEY_COPY;

-- 테이블 컬럼 수정
ALTER TABLE USER_FOREIGNKEY_COPY MODIFY USER_POINT NUMBER;
DESC USER_FOREIGNKEY_COPY;

-- 제약조건 추가, 삭제, 이름변경
DROP TABLE SHOP_BUY;
DROP TABLE SHOP_MEMBER;

CREATE TABLE SHOP_MEMBER(
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    USER_GEDNER CHAR(1),
    USER_PHONE VARCHAR2(20),
    USER_EMAIL VARCHAR2(30)
);

INSERT INTO SHOP_MEMBER VALUES (1, 'khuser01', 'pass01', '일용자', 'M', '01023445678', 'khuser01@kh.com');
SELECT * FROM SHOP_MEMBER;

-- ALTER TABLE (테이블명) ADD CONSTRAINT (제약조건 이름) (제약조건) ((칼럼명))
ALTER TABLE SHOP_MEMBER ADD CONSTRAINT UNQ_USER_NO UNIQUE(USER_NO); -- UNIQUE
ALTER TABLE SHOP_MEMBER ADD CONSTRAINT PK_USER_ID PRIMARY KEY(USER_ID); -- PRIMARY KEY
-- * NOT NULL 추가는 조금 다름
ALTER TABLE SHOP_MEMBER MODIFY USER_PWD NOT NULL; -- NOT NULL

-- 제약조건 삭제
-- 제약조건을 확인하여 이름을 알아야함 (CONSTRAINT_NAME)
ALTER TABLE SHOP_MEMBER DROP CONSTRAINT SYS_C007082;

-- 제약조건 수정 (삭제 후 추가)

-- 제약조건 확인
--**CONSTRAINT TYPE
-- P : PRIMARY KEY
-- R : FOREIGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SHOP_MEMBER';


CREATE TABLE SHOP_BUY (
    BUY_NO NUMBER, --PRIMARY KEY,
    USER_ID VARCHAR2(30), --REFERENCES SHOP_MEMBER(USER_ID) ON DELETE SET NULL,
    PRODUCT_NAME VARCHAR2(20),
    REG_DAGE DATE --DEFAULT SYSDATE
);

ALTER TABLE SHOP_BUY ADD CONSTRAINT PK_BUY_NO PRIMARY KEY(BUY_NO);
ALTER TABLE SHOP_BUY ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES SHOP_MEMBER(USER_ID);
ALTER TABLE SHOP_BUY MODIFY REG_DAGE DEFAULT SYSDATE;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SHOP_BUY';
DESC SHOP_BUY;

-- 제약조건 활성화 / 비활성화
ALTER TABLE SHOP_BUY DISABLE CONSTRAINT FK_USER_ID; -- 비활성화 (제약조건에 안걸리게 데이터 넣을 때 사용)
ALTER TABLE SHOP_BUY ENABLE CONSTRAINT FK_USER_ID; -- 활성화

-- 제약조건명 변경
ALTER TABLE SHOP_BUY RENAME CONSTRAINT PK_BUY_NO TO BUY_NO_PK;

-- 컬럼명 변경
ALTER TABLE SHOP_BUY RENAME COLUMN REG_DATE TO BUY_DATE;

-- 테이블명 변경
ALTER TABLE SHOP_BUY RENAME TO SHOP_BUY_TBL;
RENAME SHOP_BUY_TBL TO SHOP_BUY;